baseURL = 'https://sureshgehlot.vercel.app/'
languageCode = 'en-us'
title = 'Suresh Gehlot'
theme = "PaperMod"

[params]
  [params.profileMode]
    enabled = true
    title = "Suresh Gehlot" # default will be site title
    subtitle = "Law graduate tinkering with technology and finance"
    imageUrl = "https://i.imgur.com/zGCJrlZ.jpg" # optional
    imageTitle = "Title for the image" # optional
    imageWidth = 125 # custom size
    imageHeight = 120 # custom size
  
    [[params.profileMode.buttons]]
      name = "Archive"
      url = "/archive/"
    
    [[params.profileMode.buttons]]
      name = "Linkedin"
      url = "https://www.linkedin.com/in/sureshgehlot/"


     [[params.profileMode.buttons]]    
      name = "Substack"
      url =  "https://substack.com/profile/91095546-suresh-gehlot?utm_source=substack_profile"

  [params.homeInfoParams]
    Title = "Hello Stranger"
    Content = "Welcome to this website. This is my conscious digital journal"
  
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/SuresGehlot"

  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/gehlotsuresh"


  [[params.socialIcons]]
    name = "goodreads"
    url = "https://www.goodreads.com/user/show/159810341-suresh-gehlot"

  [[params.socialIcons]]
    name = "Medium"
    url = "https://sureshofgehlot.medium.com"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/gehlotsuresh"


  showbreadcrumbs = true
  showreadingtime = true
  showsharebuttons = true
  showpostnavlinks= true
  


[taxonomies]
  tag = "tags"
  category = "categories"


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "Categories"
    name = "Categories"
    url = "/Categories/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "Tags"
    name = "Tags"
    url = "/Tags/"
    weight = 4

    [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 5

    [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 6


[params.search]
    path = "/index.json"
    placeholder = "Type here to search..."
    noResultsFound = "No results found."

[outputs]
  home = ["HTML", "RSS", "JSON"]
